#!/bin/sh
set -e
cd "${APPDIR}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
EXEC="$(grep -e '^Exec=.*' "${APPDIR}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)"
exec "${APPDIR}/usr/bin/${EXEC}" "$@"
